### ISSUE TITLE
unable to run back end 

### ISSUE THREAD

**Issue by dkarthi1973** [gianantoniopini/meter-data-analytics#1]
I tried to run the external api but getting the following error 
E:\karthi\workspace\react\meter-data-analytics-master\external-api>npm run start

> meter-data-analytics-external-api@1.0.0 start
> nodemon --exec ts-node --require tsconfig-paths/register src/server.ts

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node --require tsconfig-paths/register src/server.ts`
E:\karthi\workspace\react\meter-data-analytics-master\external-api\src\server.ts:8
  throw new Error(`no PORT found in process.env`);
        ^
Error: no PORT found in process.env
    at Object.<anonymous> (E:\karthi\workspace\react\meter-data-analytics-master\external-api\src\server.ts:8:9)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (C:\Users\Asus\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Asus\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at phase4 (C:\Users\Asus\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:567:12)
    at bootstrap (C:\Users\Asus\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:85:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by gianantoniopini** [comment]
It looks like you have not created your `.env` file under the external-api directory. If that's the case, you can create one by copying file ".env.example" in the external-api directory to file ".env" .
The same applies to the back-end directory.

**Comment by dkarthi1973** [comment]
Yes, I have created .env file and execute perfectly now. thanks for your valuable inputs.

**Comment by gianantoniopini** [comment]
Glad to know you can run it now.
